apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus            # fixed UID so dashboards can reference it
    type: prometheus
    access: proxy
    isDefault: true
    url: http://host.docker.internal:9999
    jsonData:
      httpMethod: POST